import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { Alert, FlatList, Linking, StyleSheet, Text, TouchableOpacity, View } from "react-native";

import { EmptyState, IconAction, PageHeader, StatusPill } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { DeliveryStatus } from "@/lib/crm-domain";
import { useCRM } from "@/lib/crm-store";

const nextStatus: Record<DeliveryStatus, DeliveryStatus> = { packed: "out", out: "delivered", delivered: "delivered", failed: "packed" };
const nextLabel: Record<DeliveryStatus, string> = { packed: "Out for delivery", out: "Mark delivered", delivered: "Delivered", failed: "Reopen delivery" };
export default function DeliveriesScreen() { const router = useRouter(); const colors = useColors(); const { data, updateDeliveryStatus } = useCRM(); return <ScreenContainer><FlatList data={data.deliveries} keyExtractor={(delivery) => delivery.id} contentContainerStyle={styles.content} ListHeaderComponent={<PageHeader eyebrow="Delivery queue" title="Deliveries" action={<IconAction label="Back" icon="arrow-back" onPress={() => router.back()} />} />} renderItem={({ item }) => { const customer = data.customers.find((entry) => entry.id === item.customerId); const phone = customer?.phone.replace(/[^0-9]/g, "") ?? ""; return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardTop}><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{customer?.name ?? "Customer"}</Text><Text style={[styles.place, { color: colors.muted }]}>{customer?.location || "Location not saved"}</Text></View><StatusPill status={item.status} /></View><View style={styles.actions}><TouchableOpacity onPress={() => Linking.openURL(`tel:${phone}`).catch(() => Alert.alert("Phone unavailable", "This device cannot open the phone dialler."))} style={[styles.smallButton, { borderColor: colors.border }]}><MaterialIcons name="call" color={colors.primary} size={19} /><Text style={[styles.smallText, { color: colors.foreground }]}>Call</Text></TouchableOpacity><TouchableOpacity disabled={item.status === "delivered"} onPress={() => updateDeliveryStatus(item.id, nextStatus[item.status])} style={[styles.largeButton, { backgroundColor: item.status === "delivered" ? colors.border : colors.primary }]}><Text style={styles.largeText}>{nextLabel[item.status]}</Text></TouchableOpacity></View></View>; }} ItemSeparatorComponent={() => <View style={styles.separator} />} ListEmptyComponent={<EmptyState icon="local-shipping" title="No deliveries in the queue" detail="A delivery is created automatically when a new sale is recorded." />} /></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 32, flexGrow: 1 }, separator: { height: 10 }, card: { borderWidth: 1, borderRadius: 19, padding: 15 }, cardTop: { flexDirection: "row", alignItems: "flex-start", gap: 8 }, name: { fontSize: 15, fontWeight: "800" }, place: { fontSize: 12, marginTop: 4 }, actions: { flexDirection: "row", gap: 10, marginTop: 15 }, smallButton: { minHeight: 44, paddingHorizontal: 13, borderWidth: 1, borderRadius: 13, flexDirection: "row", alignItems: "center", gap: 6 }, smallText: { fontSize: 13, fontWeight: "800" }, largeButton: { flex: 1, minHeight: 44, borderRadius: 13, alignItems: "center", justifyContent: "center" }, largeText: { color: "#18130B", fontSize: 13, fontWeight: "800" } });
