import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Alert, FlatList, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";

import { EmptyState, FormInput, IconAction, PageHeader, PrimaryButton, SecondaryButton } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { money, Product } from "@/lib/crm-domain";
import { useCRM } from "@/lib/crm-store";
import { TONY_FACEBOOK_CATALOGUE } from "@/constants/catalogue";

export default function InventoryScreen() {
  const router = useRouter(); const colors = useColors(); const { data, addProduct, importProducts, adjustProduct } = useCRM(); const [adding, setAdding] = useState(false); const [name, setName] = useState(""); const [sku, setSku] = useState(""); const [cost, setCost] = useState(""); const [price, setPrice] = useState(""); const [quantity, setQuantity] = useState("");
  const importCatalogue = () => {
    const added = importProducts(TONY_FACEBOOK_CATALOGUE.map((item) => ({ name: item.name, sku: "", costPrice: 0, sellingPrice: item.sellingPrice, quantityOnHand: 0 })));
    Alert.alert(
      added > 0 ? "Fragrances added" : "Already in stock",
      added > 0
        ? `${added} fragrance${added === 1 ? "" : "s"} from Tony's Facebook list added, with selling prices. Set each one's stock quantity with the + button, and its cost price by re-adding it if you want profit to be exact.`
        : "All of Tony's Facebook fragrances are already in your stock.",
    );
  };
  const save = () => { const costPrice = Number(cost); const sellingPrice = Number(price); const quantityOnHand = Number(quantity); if (!name.trim() || !Number.isFinite(costPrice) || !Number.isFinite(sellingPrice) || !Number.isFinite(quantityOnHand) || quantityOnHand < 0) return Alert.alert("Complete product details", "Enter a perfume name, cost price, selling price, and stock quantity."); addProduct({ name: name.trim(), sku: sku.trim(), costPrice, sellingPrice, quantityOnHand }); setName(""); setSku(""); setCost(""); setPrice(""); setQuantity(""); setAdding(false); };
  if (adding) return <ScreenContainer><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><PageHeader eyebrow="Stock control" title="Add perfume" action={<IconAction label="Close" icon="close" onPress={() => setAdding(false)} />} /><FormInput label="Perfume name" value={name} onChangeText={setName} placeholder="e.g. White Oud 50ml" /><FormInput label="SKU / code" value={sku} onChangeText={setSku} placeholder="Optional product code" /><FormInput label="Cost price (BWP)" value={cost} onChangeText={setCost} placeholder="0.00" keyboardType="decimal-pad" /><FormInput label="Selling price (BWP)" value={price} onChangeText={setPrice} placeholder="0.00" keyboardType="decimal-pad" /><FormInput label="Quantity in stock" value={quantity} onChangeText={setQuantity} placeholder="0" keyboardType="numeric" /><PrimaryButton title="Save perfume" icon="check" onPress={save} /></ScrollView></ScreenContainer>;
  return <ScreenContainer><FlatList data={data.products} keyExtractor={(product) => product.id} contentContainerStyle={styles.content} ListHeaderComponent={<PageHeader eyebrow="Stock control" title="Inventory" action={<IconAction label="Back" icon="arrow-back" onPress={() => router.back()} />} />} renderItem={({ item }) => <ProductRow product={item} onDecrease={() => adjustProduct(item.id, -1)} onIncrease={() => adjustProduct(item.id, 1)} />} ItemSeparatorComponent={() => <View style={styles.separator} />} ListEmptyComponent={<EmptyState icon="inventory-2" title="No perfumes saved" detail="Add each perfume with its cost, selling price, and quantity to keep stock and profit accurate." action={<View style={{ width: "100%", gap: 10 }}><PrimaryButton title="Add first perfume" icon="add" onPress={() => setAdding(true)} /><SecondaryButton title="Import Tony's Facebook list (13)" icon="cloud-download" onPress={importCatalogue} /></View>} />} ListFooterComponent={data.products.length > 0 ? <View style={[styles.footer, { gap: 10 }]}><PrimaryButton title="Add perfume" icon="add" onPress={() => setAdding(true)} /><SecondaryButton title="Import Tony's Facebook list (13)" icon="cloud-download" onPress={importCatalogue} /></View> : null} /></ScreenContainer>;
}
function ProductRow({ product, onDecrease, onIncrease }: { product: Product; onDecrease: () => void; onIncrease: () => void }) { const colors = useColors(); return <View style={[styles.product, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={{ flex: 1 }}><Text style={[styles.productName, { color: colors.foreground }]}>{product.name}</Text><Text style={[styles.productMeta, { color: colors.muted }]}>{product.sku || "No SKU"} · Cost {money(product.costPrice)} · Sell {money(product.sellingPrice)}</Text></View><View style={styles.stock}><TouchableOpacity onPress={onDecrease} style={[styles.stockButton, { borderColor: colors.border }]}><MaterialIcons name="remove" color={colors.foreground} size={18} /></TouchableOpacity><Text style={[styles.stockNumber, { color: product.quantityOnHand <= 3 ? colors.error : colors.foreground }]}>{product.quantityOnHand}</Text><TouchableOpacity onPress={onIncrease} style={[styles.stockButton, { borderColor: colors.border }]}><MaterialIcons name="add" color={colors.foreground} size={18} /></TouchableOpacity></View></View>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 32, flexGrow: 1 }, separator: { height: 10 }, footer: { marginTop: 16 }, product: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: "row", alignItems: "center", gap: 10 }, productName: { fontSize: 15, fontWeight: "800" }, productMeta: { fontSize: 11, lineHeight: 17, marginTop: 4 }, stock: { alignItems: "center", gap: 4 }, stockButton: { height: 28, width: 28, borderRadius: 10, borderWidth: 1, alignItems: "center", justifyContent: "center" }, stockNumber: { fontSize: 14, fontWeight: "800" } });
