import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";

import { PageHeader, SectionTitle } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useCRM } from "@/lib/crm-store";

export default function MoreScreen() {
  const colors = useColors();
  const router = useRouter();
  const { data } = useCRM();
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><PageHeader eyebrow="Business controls" title="More" /><View style={styles.brandCard}><Text style={[styles.brandMonogram, { color: colors.primary }]}>TF</Text><View><Text style={styles.brandName}>{data.businessName}</Text><Text style={styles.brandMeta}>Private offline business workspace</Text></View></View><SectionTitle title="Manage your business" /><View style={[styles.menu, { backgroundColor: colors.surface, borderColor: colors.border }]}><MenuItem icon="inventory-2" title="Inventory" detail="Perfumes, cost price and stock" onPress={() => router.push("/inventory")} /><MenuItem icon="local-shipping" title="Deliveries" detail="Location and delivery status" onPress={() => router.push("/deliveries")} /><MenuItem icon="receipt-long" title="Invoices" detail="Create and share customer invoices" onPress={() => router.push("/(tabs)/sales")} /><MenuItem icon="settings" title="Business settings" detail="Invoice prefix and business details" onPress={() => Alert.alert("Business settings", "Your invoice prefix is TF. A dedicated settings screen is planned after the core workflow is in daily use.")} /></View><SectionTitle title="Protection" /><View style={[styles.protection, { backgroundColor: `${colors.primary}16`, borderColor: `${colors.primary}45` }]}><MaterialIcons name="phonelink-lock" color={colors.primary} size={23} /><View style={{ flex: 1 }}><Text style={[styles.protectionTitle, { color: colors.foreground }]}>Records stay on this phone</Text><Text style={[styles.protectionDetail, { color: colors.muted }]}>Customer, sales, delivery, and finance records work offline. Include data backup before using a second phone.</Text></View></View></ScrollView></ScreenContainer>;
}

function MenuItem({ icon, title, detail, onPress }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; detail: string; onPress: () => void }) { const colors = useColors(); return <TouchableOpacity onPress={onPress} style={styles.menuItem}><View style={[styles.menuIcon, { backgroundColor: `${colors.primary}1C` }]}><MaterialIcons name={icon} color={colors.primary} size={21} /></View><View style={{ flex: 1 }}><Text style={[styles.menuTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.menuDetail, { color: colors.muted }]}>{detail}</Text></View><MaterialIcons name="chevron-right" color={colors.muted} size={22} /></TouchableOpacity>; }

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 32 }, brandCard: { backgroundColor: "#17130F", borderRadius: 22, padding: 18, flexDirection: "row", alignItems: "center", gap: 13 }, brandMonogram: { fontSize: 20, fontWeight: "900", letterSpacing: -1, width: 47, height: 47, borderRadius: 16, borderWidth: 1, borderColor: "#B99235", textAlign: "center", textAlignVertical: "center" }, brandName: { color: "#FFF9F0", fontSize: 17, fontWeight: "800" }, brandMeta: { color: "#C8BBAB", fontSize: 12, marginTop: 3 }, menu: { borderWidth: 1, borderRadius: 20, overflow: "hidden" }, menuItem: { minHeight: 78, padding: 14, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#E7DED2" }, menuIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, menuTitle: { fontSize: 15, fontWeight: "800" }, menuDetail: { fontSize: 12, marginTop: 3 }, protection: { borderWidth: 1, borderRadius: 19, padding: 16, flexDirection: "row", gap: 12, alignItems: "flex-start" }, protectionTitle: { fontSize: 14, fontWeight: "800" }, protectionDetail: { fontSize: 12, lineHeight: 17, marginTop: 4 } });
